version: 'v2.31.0-desktop.2'

services:
  bookstallDB:
    container_name: bookstall_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_NEST_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bookstallDB_data:/var/lib/postgresql/data
volumes:
  bookstallDB_data:
